spring.application.name=taskmanager

# Configuration Database
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=${DB_USERNAME:lost}
spring.datasource.password=${DB_PASSWORD:1984}


# Development environment example ## create-drop para dev.
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
