spring.application.name=taskmanager

# Configuration Database
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=lost
spring.datasource.password=1984


# Development environment example ## create-drop para dev.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
