spring.application.name=taskmanager

spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=lost
spring.datasource.password=1984

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
